#!/bin/bash

alias c="clear"
alias ifc="sudo ifconfig"
alias e="exit"
alias ll="ls -la"

#Support git command

function ladd() {
	git add .
}

function lcm() {
	git commit	
}

function lst() {
	git status
}

function lph() {
	if [[ $# != 2 ]]; then
		git push
		return $?
	fi

	git push $1 $2
}

function gd() {
	git diff
}

# XClip
# Copy to clipboard 
alias pbcopy="xclip -selection clipboard"